# Generated by Django 4.2.1 on 2023-05-31 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontologico', '0004_estrategia_mision_vision_tactica_objetivo_meta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta',
            name='objetivo',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='tactica',
        ),
        migrations.RemoveField(
            model_name='objetivo',
            name='estrategia',
        ),
        migrations.RemoveField(
            model_name='objetivo',
            name='vision',
        ),
        migrations.RemoveField(
            model_name='tactica',
            name='estrategia',
        ),
        migrations.RemoveField(
            model_name='vision',
            name='mision',
        ),
        migrations.DeleteModel(
            name='Estrategia',
        ),
        migrations.DeleteModel(
            name='Meta',
        ),
        migrations.DeleteModel(
            name='Mision',
        ),
        migrations.DeleteModel(
            name='Objetivo',
        ),
        migrations.DeleteModel(
            name='Tactica',
        ),
        migrations.DeleteModel(
            name='Vision',
        ),
    ]
