# Generated by Django 4.2.1 on 2023-06-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estructuras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccionejecutiva',
            name='tipo',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
