# Generated by Django 4.2.1 on 2023-05-31 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontologico', '0003_nivel_alter_pago_options_prueba_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': 'Estrategia',
                'verbose_name_plural': 'Estrategias',
            },
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': 'Mision',
                'verbose_name_plural': 'Misiones',
            },
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=400)),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontologico.mision')),
            ],
            options={
                'verbose_name': 'Vision',
                'verbose_name_plural': 'Visiones',
            },
        ),
        migrations.CreateModel(
            name='Tactica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=400)),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontologico.estrategia')),
            ],
            options={
                'verbose_name': 'Tactica',
                'verbose_name_plural': 'Tacticas',
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=400)),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontologico.estrategia')),
                ('vision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontologico.vision')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=400)),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontologico.objetivo')),
                ('tactica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontologico.tactica')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
            },
        ),
        migrations.AddField(
            model_name='estrategia',
            name='mision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontologico.mision'),
        ),
    ]
