# Generated by Django 4.2.1 on 2023-06-02 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetonegocio',
            name='material',
        ),
        migrations.DeleteModel(
            name='VentaMaterial',
        ),
    ]
