# Generated by Django 4.2.1 on 2023-05-31 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ontologico', '0005_remove_meta_objetivo_remove_meta_tactica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('cedula', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actores',
            },
        ),
        migrations.CreateModel(
            name='BullUnillanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Bull Unillanos',
            },
        ),
        migrations.CreateModel(
            name='EmisionCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado', models.CharField(max_length=150)),
                ('fecha', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emision de certificado',
            },
        ),
        migrations.CreateModel(
            name='LineaNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('bull', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.bullunillanos')),
            ],
            options={
                'verbose_name': 'Linea de negocio',
            },
        ),
        migrations.CreateModel(
            name='ObjetoNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('tipo', models.CharField(max_length=60)),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.emisioncertificado')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontologico.curso')),
            ],
            options={
                'verbose_name': 'Objeto de negocio',
            },
        ),
        migrations.CreateModel(
            name='VentaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('tipo', models.CharField(max_length=12)),
                ('valor', models.FloatField()),
            ],
            options={
                'verbose_name': 'Venta de material didactico',
            },
        ),
        migrations.CreateModel(
            name='ServicioNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=300)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.actor')),
                ('bull', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.bullunillanos')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.lineanegocio')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.objetonegocio')),
            ],
            options={
                'verbose_name': 'Servicio de negocio',
            },
        ),
        migrations.AddField(
            model_name='objetonegocio',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.ventamaterial'),
        ),
        migrations.AddField(
            model_name='actor',
            name='bull',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.bullunillanos'),
        ),
    ]
